name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Draft file-routes release
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter-file-routes.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Draft performance-monitor release
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter-performance-monitor.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
